### ISSUE TITLE
emit `unhandledRejection` and `handledRejection` events

### ISSUE THREAD

**Issue by jamestalmage** [floatdrop/pinkie#3]
https://nodejs.org/api/process.html#process_event_unhandledrejection

**Comment by floatdrop** [comment]
Yes, this should be supported.

**Comment by sindresorhus** [comment]
:+1: It's very hard to debug uncaught promises without this.

I'm using [loud-rejection](https://github.com/sindresorhus/loud-rejection) for my CLIs now, so I experience this pretty often.

**Comment by vitaly-t** [comment]
I would suggest to reflect on why this library was written in the first place...

I liked it a lot because in my mind it is an excellent blueprint to the very basic implementation of the promise standard, nothing more.

Trying to add usability features to it is to follow the path of the other monstrous promise libraries like Bluebird.

Right now it is a great educational piece, and I think it should be maintained that way, short, concise, and straight to the point.

**Comment by sindresorhus** [comment]
@vitaly-t We're talking two minor events that will massively help with debugging.
